export const authConstant = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

export const registerConstants = {
  USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE'
}

export const categoryConstant = {
  GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
  GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
  GET_ALL_CATEGORIES_FAILURE: 'GET_ALL_CATEGORIES_FAILURE'
}
export const initialDataConstant = {
  GET_ALL_INITIAL_DATA_REQUEST: 'GET_ALL_INITIAL_DATA_REQUEST',
  GET_ALL_INITIAL_DATA_SUCCESS: 'GET_ALL_INITIAL_DATA_SUCCESS',
  GET_ALL_INITIAL_DATA_FAILURE: 'GET_ALL_INITIAL_DATA_FAILURE'
}

export const postConstants = {
  GET_ALL_POSTS_REQUEST: ' GET_ALL_POSTS_REQUESTS',
  GET_ALL_POSTS_SUCCESS: ' GET_ALL_POSTS_SUCCESS',
  GET_ALL_POSTS_FAILURE: ' GET_ALL_POSTS_FAILURE',

  GET_SINGLE_POST_REQUEST: ' GET_SINGLE_POST_REQUEST',
  GET_SINGLE_POST_SUCCESS: ' GET_SINGLE_POST_SUCCESS',
  GET_SINGLE_POST_FAILURE: ' GET_SINGLE_POST_FAILURE',

  UPDATE_POST_REQUEST: ' GET_ALL_POSTS_REQUESTS',
  UPDATE_POST_SUCCESS: ' GET_ALL_POSTS_SUCCESS',
  UPDATE_POST_FAILURE: ' GET_ALL_POSTS_FAILURE',

  DELETE_POST_REQUEST: ' DELETE_POST_REQUEST',
  DELETE_POST_SUCCESS: ' DELETE_POST_SUCCESS',
  DELETE_POST_FAILURE: ' DELETE_POST_FAILURE'
}
export const deleteUserConstant = {
  DELETE_USER_REQUEST: ' DELETE_USER_REQUEST',
  DELETE_USER_SUCCESS: ' DELETE_USER_SUCCESS',
  DELETE_USER_FAILURE: ' DELETE_USER_FAILURE'
}
export const updateUserConstant = {
  UPDATE_USER_REQUEST: ' UPDATE_USER_REQUEST',
  UPDATE_USER_SUCCESS: ' UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILURE: ' UPDATE_USER_FAILURE'
}
